### ISSUE TITLE
no implicit conversion of URI::Generic into String in picture.rb

### ISSUE THREAD

**Issue by yegor256** [yegor256/jekyll-bits#9]
```
: TypeError: no implicit conversion of URI::Generic into String
/Volumes/ssd2/code/jekyll-bits/lib/jekyll-bits/picture.rb:85:in `+'
/Volumes/ssd2/code/jekyll-bits/lib/jekyll-bits/picture.rb:85:in `uri'
/Volumes/ssd2/code/jekyll-bits/lib/jekyll-bits/picture.rb:34:in `jb_picture_head'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.1`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/jekyll-bits#9` was not in scope
